# Theme version
version: 1.2.0

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

# Sidebar
widgets:
  - search
  - category
  - tag
  - archive
  - recent_posts
  - recent_comments
  ##- weibo
  - links

# Static files
js: js
css: css

# Extensions
Plugins:
  hexo-generator-feed
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.
swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293

#Cmments
duoshuo: ## Your duoshuo_shortname, e.g. username
disqus: ## Your disqus_shortname, e.g. username

# About page 
about:
  photo_url: 233.jpg ## Your photo e.g. http://obzf7z93c.bkt.clouddn.com/themeauthor.jpg
  email: ishuzb@foxmail.com ## Your email e.g.  
  weibo_url: http://weibo.com/6142874868/profile?topnav=1&wvr=6&is_all=1 
  weibo_name: 胡支波 ## Your weibo's name e.g.  秋过冬漫长
  github_url: https://github.com/strivebo ## Your github'url e.g.  https://github.com/chaooo
  github_name: strivebo ## Your github'name e.g.  chaooo

# Friend link
links:
  - title: 我的CSDN地址
    url: http://www.example1.com/
  - title: 百度
    url: http://www.baidu.com/
  - title: site-name3
    url: http://www.example3.com/


# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
